---
- hosts: jukebox
  become: yes
  vars: {}
  pre_tasks:
    - name: change hostname according to inventory
      hostname:
        name: '{{ inventory_hostname_short }}'
  roles:
    - role: mount
  tasks: []
