---
mount_directory: /music/
mount_drive: /dev/loop0  # noop for testing

mount_systemd_unit_prefix: '{{ mount_directory|replace("/","-")|trim("-") }}'
mount_systemd_unit_suffix:
  - mount
  - automount
