name: molecule-tests
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
    schedule:
      - cron: '18 19 3,13,23 * *'


jobs:
  test:
    runs-on: ubuntu-latest
    container: potyarkin/cirrus-run
    env:
      CIRRUS_API_TOKEN: ${{ secrets.CIRRUS_API_TOKEN }}
      CIRRUS_GITHUB_REPO: sio/.cirrus-ci-jobs
      CIRRUS_SHOW_BUILD_LOG: always
    steps:
      - uses: actions/checkout@v1
      - run:  cirrus-run .ci/cirrus.yml.j2
