name: molecule-tests
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
    schedule:
      - cron: '18 19 3,13,23 * *'


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: cache/pip
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: cache
          key: >
            cache-v1
            ${{ runner.os }}
            ${{ hashFiles('requirements.txt') }}
            ${{ hashFiles('tests/requirements.txt') }}
      - run: make -C tests
